apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            if obj.status.health == "Progressing" then
              hs.status = "Progressing"
              hs.message = ""
            elseif obj.status.health == "Missing" then
              hs.status = "Degraded"
              hs.message = obj.status.health.message
            else
              hs.status = obj.status.health.status
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
