apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
  - git:
      repoURL: https://github.com/mikutas/app-of-apps-with-helm-experiment
      revision: main
      directories:
      - path: apps/*
  template:
    spec:
      source:
        targetRevision: main
        helm:
          valueFiles:
          - values/production.values.yaml
