apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fuga
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/mikutas/app-of-apps-with-helm-experiment
    path: helm/fuga
    targetRevision: {{ .Values.fuga.targetRevision }}
    helm:
      values: {}
